server.port: 8080

addressClient:
  baseUrl: http://customer-service:8081

customerClient:
  baseUrl: http://customer-service:8081

spring:
  application:
    name: api-service

management:
  tracing:
    sampling:
      probability: 1
  otlp:
    tracing:
      endpoint: http://collector:4317
      transport: grpc