services:

  api-service:
    build: api-service/
    image: api-service:latest
    links:
      - collector
    ports:
      - "8086:8080"

  customer-service:
    build: ./customer-service/
    image: customer-service:latest
    links:
      - collector
    ports:
      - "8087:8080"

  # Collection doesn't work yet as this jaeger doesn't like the open telemetry traces
  collector:
    image: jaegertracing/all-in-one
    ports:
      - "5778:5778"
      - "5779:5779"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
    environment:
#      COLLECTOR_OTLP_ENABLED: "true" # Not sure this is needed
      RECEIVERS_OTLP_PROTOCOLS_GRPC_ENDPOINT: "0.0.0.0:4317"
      RECEIVERS_OTLP_PROTOCOLS_HTTP_ENDPOINT: "x.0.0.0:4318"
#      SERVICE_PIPELINES_TRACES_RECEIVERS: "otlp"


#  collector:
#    image: logzio/otel-collector-traces
#    environment:
#      - LOGZIO_REGION=${LOGZIO_REGION}
#      - LOGZIO_TRACES_TOKEN=${LOGZIO_TRACES_TOKEN}
#    ports:
#      - "1777:1777"
#      - "9411:9411"
#      - "9943:9943"
#      - "6831:6831"
#      - "6832:6832"
#      - "14250:14250"
#      - "14268:14268"
#      - "4317:4317"
#      - "55681:55681"
#      - "8888:8888"