server.port: 8081

spring:
  application:
    name: customer-service

management:
  tracing:
    sampling:
      probability: 1
    baggage:
      remote-fields: use-case-baggage # incoming headers to read as baggage
      tag-fields: use-case-baggage # baggage to add to trace info submitted to jaeger
  otlp:
    tracing:
      endpoint: http://collector:4317
      transport: grpc
