server.port: 8081

spring:
  application:
    name: customer-service

management:
  tracing:
    sampling:
      probability: 1
  otlp:
    tracing:
      endpoint: http://collector:4317
      transport: grpc
