server.port: 8081

spring:
  output:
    ansi:
      enabled: always
  application:
    name: customer-service

management:
  tracing:
    sampling:
      probability: 1
  otlp:
    tracing:
      endpoint: http://collector:4317
      transport: grpc